### PR TITLE
Csvhandlerpolar

### PR DESCRIPTION
**Pull request by mathysgrapotte**
There are now two classes for handling csv, CsvParser (for parsing the data, doing noising etc.) and CsvLoader (for loading the data into models). Additionally both now inherit from the same CsvHandler class. 

Then, Polars has replaced Pandas as it is much faster.

### CODE REVIEW

**Comment by mathysgrapotte** [comment]
Please do not delete branch as it requires testing of some functionalities.

**Comment by mathysgrapotte** [comment]
branch can be deleted

**Review by suzannejin — APPROVED** [review]

**Comment by alessiovignoli** [comment]
The metadata now is the belonging to one of the sets. But is the split function (selected by user) going to assign this value modifying the csv in input?

**Comment by mathysgrapotte** [comment]
Yes, the split:meta:field is special, it will be added or modified by the CsvParser but can also be passed by the user in the input csv

**Comment by alessiovignoli** [comment]
ok i like it but the skip of split when user passes it should be handled correctly. Can you open a issue for it?

**Comment by alessiovignoli** [comment]
the first error is more than fine because it caver cases in which the user did not specify neither manually neither explicitly a splitter scheme. I would like to have another error in case that column already exist and the split mthod is called on such a csv. Going something like "a split meta column is already present but a splitter function has been called. remove the split meta column if you want to call a split function."

**Pull request merged**
